### ISSUE TITLE
triton profile create should handle private key that is passphrase-protected

### ISSUE THREAD

**Issue by askfongjojo** [joyent/node-triton#108]
$ triton profile create
A profile name. A short string to identify a CloudAPI endpoint to the
`triton` CLI.
name: angela.fong.east3b

The CloudAPI endpoint URL.
url: https://us-east-3b.api.joyent.com

Your account login name.
account: angela.fong

The fingerprint of the SSH key you have registered for your account.
Alternatively, You may enter a local path to a public or private SSH key to
have the fingerprint calculated for you.
keyId: ~/.ssh/id_rsa
Failed to parse (unnamed) as a valid pem format key: PEM key is encrypted
(password-protected). Please use the SSH agent or decrypt the key.
keyId: ~/.ssh/id_rsa_nopassphrase
Fingerprint: e8:da:41:32:5c:ac:2e:6e:20:c9:05:8f:a7:2b:7e:bd

**Comment by deserat** [comment]
+1

**Comment by daachi** [comment]
This is made unnecessarily confusing because of the error message. If you give `triton profile create` the public key (i.e. id_rsa.pub) of a passphrase protected ssh key, the command will complete successfully.

The sshpk-agent library is installed but is not currently being used by triton, so the error message that suggest using SSH agent is also misleading.

Just changing the wording of the error message(s) would likely cut down on a lot of frustration. It's possible but I think completely unnecessary to add sshpk-agent functionality.

**Comment by arekinath** [comment]
@daachi I think this would be better fixed by actually supporting encrypted keys properly (everywhere in node-triton) and redoing a lot of this code -- particularly, redoing it with ssh-agent users in mind. Currently you can provide a path to a key in this step that node-triton will not actually be able to use later (e.g. you can give it `/tmp/foo.id_rsa` and it will blow up later when it tries to test using it because actually the key has to be in `$HOME/.ssh` or in the agent) -- which is not great UI. It should really present a list of keys to you that it knows it can actually use and prompt you to choose one -- I have patches for smartdc-auth and this repo in development that do exactly this (they've just been on the backburner because of other high-priority work lately, for which I apologise)

The fact that the "docker" command can only operate with an unencrypted key *on disk* is an annoying wrinkle here, though. One idea that's been suggested is to let "triton profile create" prompt you with the option of generating a secondary key just for docker and adding it to your account. Or maybe (for the more paranoid), enabling an option whereby you can generate a temporary key and cert for docker that is only valid for, say, some number of hours and you run a node-triton command to renew it before each time you want to use docker. I don't know how worthwhile either of those last options would be, but it would be nice to not punish people for trying to do better at key security on their laptops by just saying "sorry you can't use docker" or just silently storing a second copy of their keys unencrypted.

**Comment by arekinath** [comment]
fwiw, [this](https://gist.github.com/arekinath/1a5ff08094a504eaf200d7d2c43c9a02) is what the code in https://cr.joyent.us/#/c/178/ currently looks like when run. I'm waiting for @trentm to be back in the office to get his review on it (it might need some more cleaning up or changes)

**Comment by daachi** [comment]
I really like the way you're handling the ssh keys, but frankly aghast at this:

`WARNING: Docker does not support encrypted (password protected) keys. If you
continue, a decrypted copy of your SSH private key will be stored on disk for [use]
with Docker.`

I feel like no sensible person would allow this. I haven't worked much with docker, but I've never run into this issue with the work I have done. Is this triton specific or, is it specific to docker?

**Comment by arekinath** [comment]
@daachi It's an issue specific to docker, and there's no workaround -- it just refuses to even look at encrypted keys. You can use `triton profile create --no-docker` or just refuse to enter your password at the new prompt and `triton` will skip setting up docker for your profile. One option I've been considering to improve the situation a little is to make node-triton offer to create a second key for you just for docker so that your regular SSH key can stay encrypted. Unfortunately docker uses the Go TLS library, not OpenSSL or GnuTLS, so PKCS#11 is off the table.

As an aside, the PEM passphrase crypto that `ssh-keygen` and `openssl genrsa` use is very weak anyway -- the KDF amounts to a single round of MD5. A single desktop-class GPU can break any 10-char passphrase on it in about a day, and large clusters make any passphrase shorter than about 25 chars (and any combination of modified dictionary words up to about 6 words) breakable in a very reasonable time. OpenSSH have started working on this in the last few releases, with a new internal private key format (which is now the default for ed25519 keys) that uses a bcrypt-like KDF that's much more resistant to brute force. I'm planning to add full support for this to sshpk soon (it already supports the format, just not the crypto on it yet).

**Comment by foxx** [comment]
Am I correct in saying that you simply cannot use Docker with Triton if your keys are password protected? Annoyingly I couldn't find any reference to this lack of feature in any of the Docker github repos, does anyone know where this issue has been raised?

There's some discussion in https://github.com/docker/docker/issues/7667, which talks about using https://github.com/xogeny/sdocker which tunnels Docker over SSH.

Another issue https://github.com/docker/docker/issues/7650 touches on using SSH keys for Docker socket authentication, but it was closed out by core devs citing "it's not among our goals right now to tackle this."

Although @arekinath makes some interesting points regarding PEM passphrase crypto,  removing the passphrase still feels like a step down in terms of security, especially for those of us with very secure passwords. The patch in https://cr.joyent.us/#/c/178/ looks like a step forward for clarity of the problem, but it would be much better if the problem wasn't there at all.

**Comment by arekinath** [comment]
@foxx This is the problem in the official Docker client, not anything in Triton. The official Docker commandline client rejects password protected keys. There is no known workaround.

**Comment by arekinath** [comment]
@foxx Also note that the idea of using an SSH transport in Docker is unrelated to this particular problem. We give the keys to docker in the X.509 PEM format that it uses for normal TLS mutual authentication -- there is no SSH involved (it's just a convenient format for managing and storing keys as far as our tools are concerned).

**Comment by trentm** [comment]
https://cr.joyent.us/#/c/1025

**Comment by cburroughs** [comment]
Support for passphrase protected keys has landed in master.  See the [CHANGELOG](https://github.com/joyent/node-triton/blob/ad7d6080113daaca5f40ece575535e41d2343d4e/CHANGES.md) for details (it turned out to require some rather significant adjacent work).  As part of this I have tried to make the documentation around this feature more explicit.

Several tickets are open for followup:
 * #150
 * #151 
 * #152

**Comment by trentm** [comment]
Thanks @cburroughs for getting all this work done.
