### ISSUE TITLE
`triton instance fwrule list` and `triton fwrules` are not recognized

### ISSUE THREAD

**Issue by askfongjojo** [joyent/node-triton#133]
Just noticed two minor inconsistencies with fwrule while updating docs:
1. Expect `triton instance <object> list` and `triton instance <objects>` to both work

```
$ triton instance tag list 0fae7c30
{
    "sdc_docker": true
}
$ triton instance tags 0fae7c30
{
    "sdc_docker": true
}

$ triton instance fwrule list 0fae7c30
triton instance: error (UnknownCommand): unknown command: "fwrule"
Did you mean this?
    fwrules
$ triton instance fwrules 0fae7c30
SHORTID                               ENABLED  GLOBAL  RULE
621c4a7e-794b-4834-985c-fb3e45e38c2f  true     true    FROM any TO all vms ALLOW icmp TYPE 8 CODE 0
56911662-3664-4325-87a8-02b49bdbe370  true     -       FROM tag sdc_docker TO tag sdc_docker ALLOW tcp PORT all
27998489-e0bc-4f0f-aaaa-cdb5df79aae8  true     -       FROM tag sdc_docker TO tag sdc_docker ALLOW udp PORT all
```
1. Expect `triton <object> list` and `triton <objects>` to both work

```
$ triton fwrules
triton: error (UnknownCommand): unknown command: "fwrules"
Did you mean this?
    fwrule
$ triton fwrule list
SHORTID   ENABLED  GLOBAL  RULE
ee9902f3  false    -       FROM any TO tag bar = false ALLOW tcp PORT 22
dc291aa0  false    -       FROM any TO tag foo = false ALLOW tcp PORT 22
...
```

**Comment by YangYong3** [comment]
https://cr.joyent.us/#/c/963/

**Comment by trentm** [comment]
@askfongjojo and others: Opinions welcome.

1. The initial reason that "triton instance fwrule ..." doesn't exist is that the *only* action available on an instance's fwrules is "list" and I shied away from having a sub-sub-command just for "triton instance fwrule list".  The Q is whether it is MORE confusing to not have "triton instance fwrule list" because we tend to have it for other sub-commands.   Anyway, I'm cool adding it.

2. I'm fine adding "triton fwrules" as a shortcut for "triton fwrule list".

**Comment by trentm** [comment]
Thanks, @YangYong3 !
